### PR TITLE
Make the BINDING-TABLE-VAR "the source of truth" when specified.

### PR DESCRIPTION
**Pull request by Gleefre**
(!) Minor incompatible change: when `:binding-table-var` is specified, the `binding-table` slot of the namespace created is set to `nil` and is not used by readers or writers.

Reason: if you bind the `binding-table-var` to a new value, currently it won't mean anything, as everything depends on the `binding-table` slot. This is fine if you always have only one environment, but if you want to be able to dynamically bind the environment, you need all sort of readers/writers to use the `binding-table-var` instead of the `binding-slot` of the namespace structure. That however means, that this slot doesn't really have any meaning, as it is not updated in any way when you bind the `binding-table-var`.

The `binding-table` slot could hold to the "most global" environment of the namespace, but IMHO that would be misleading.

### CODE REVIEW

**Comment by phoe** [comment]
Sure. Would you mind documenting this change?

**Comment by Gleefre** [comment]
I somewhat documented this change, although I'm not sure if it is well-written.

**Comment by phoe** [comment]
Merged and fixed the docs. Thanks!

**Comment by Gleefre** [comment]
Thanks!

**Pull request merged**
